# 1. Limpieza y transformación de los datos.

1.1. Importar la librería pandas y darle el diminutivo de pd

In [1]:
import pandas as pd

1.2. Importar los datos ``'fbref_laliga21.csv'`` desde la ruta de tu google drive o traerlos directamente desde el ordenador y ver las 5 primeras filas del dataframe.

In [2]:
liga21 = pd.read_csv('fbref_laliga21.csv')
liga21.head(5)

,Rk,Player,Nation,Pos,Squad,Age,Born,MP,Starts,Min,...,xG,npxG,xA,npxG+xA,xG.1,xA.1,xG+xA,npxG.1,npxG+xA.1,Matches
0,1,Sabit Abdulai\Sabit-Abdulai,gh GHA,MF,Getafe,21,1999,3,0,60,...,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00,Matches
1,2,Marcos Acuña\Marcos-Acuna,ar ARG,DF,Sevilla,28,1991,30,26,2330,...,1.1,1.1,2.8,4.0,0.04,0.11,0.15,0.04,0.15,Matches
2,3,Bobby Adekanye\Bobby-Adekanye,nl NED,FWMF,Cádiz,21,1999,3,0,36,...,0.2,0.2,0.0,0.2,0.43,0.00,0.43,0.43,0.43,Matches
3,4,Martin Agirregabiria\Martin-Agirregabiria,es ESP,DFMF,Alavés,24,1996,26,16,1558,...,0.2,0.2,0.9,1.1,0.01,0.05,0.06,0.01,0.06,Matches
4,5,Joseph Aidoo\Joseph-Aidoo,gh GHA,DF,Celta Vigo,24,1995,25,14,1289,...,0.8,0.8,0.6,1.4,0.06,0.04,0.10,0.06,0.10,Matches

1.3. Obtener el tamaño del dataframe, cuantas filas y columnas tiene.

In [3]:
liga21.shape

(582, 33)

1.4. Acceder al nombre de las  columnas.

In [4]:
liga21.columns

Index(['Rk', 'Player', 'Nation', 'Pos', 'Squad', 'Age', 'Born', 'MP', 'Starts',
       'Min', '90s', 'Gls', 'Ast', 'G-PK', 'PK', 'PKatt', 'CrdY', 'CrdR',
       'Gls.1', 'Ast.1', 'G+A', 'G-PK.1', 'G+A-PK', 'xG', 'npxG', 'xA',
       'npxG+xA', 'xG.1', 'xA.1', 'xG+xA', 'npxG.1', 'npxG+xA.1', 'Matches'],
      dtype='str')

1.5.  Mirar el formato de las columnas, para comprobar si hay alguna columnas numérica que se encuentra en formato string.

In [5]:
liga21.info()

<class 'pandas.DataFrame'>
RangeIndex: 582 entries, 0 to 581
Data columns (total 33 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Rk         582 non-null    int64
 1   Player     582 non-null    str
 2   Nation     582 non-null    str
 3   Pos        582 non-null    str
 4   Squad      582 non-null    str
 5   Age        582 non-null    int64
 6   Born       582 non-null    int64
 7   MP         582 non-null    int64
 8   Starts     582 non-null    int64
 9   Min        582 non-null    int64
 10  90s        582 non-null    float64
 11  Gls        582 non-null    int64
 12  Ast        582 non-null    int64
 13  G-PK       582 non-null    int64
 14  PK         582 non-null    int64
 15  PKatt      582 non-null    int64
 16  CrdY       582 non-null    int64
 17  CrdR       582 non-null    int64
 18  Gls.1      582 non-null    float64
 19  Ast.1      582 non-null    float64
 20  G+A        582 non-null    float64
 21  G-PK.1     582 non-null    float64
 22  G+A-PK     582 non-null    float64
 23  xG         580 non-null    float64
 24  npxG       580 non-null    float64
 25  xA         580 non-null    float64
 26  npxG+xA    580 non-null    float64
 27  xG.1       580 non-null    float64
 28  xA.1       580 non-null    float64
 29  xG+xA      580 non-null    float64
 30  npxG.1     580 non-null    float64
 31  npxG+xA.1  580 non-null    float64
 32  Matches    582 non-null    str
dtypes: float64(15), int64(13), str(5)
memory usage: 150.2 KB

1.6. Cuántos valores NAN tenemos, en caso de que hayan sustituido por cero y volver a mirar la cantidad de valores nan para comprobar que ya no tenemos.

In [6]:
liga21.isna().sum()

Rk           0
Player       0
Nation       0
Pos          0
Squad        0
Age          0
Born         0
MP           0
Starts       0
Min          0
90s          0
Gls          0
Ast          0
G-PK         0
PK           0
PKatt        0
CrdY         0
CrdR         0
Gls.1        0
Ast.1        0
G+A          0
G-PK.1       0
G+A-PK       0
xG           2
npxG         2
xA           2
npxG+xA      2
xG.1         2
xA.1         2
xG+xA        2
npxG.1       2
npxG+xA.1    2
Matches      0
dtype: int64

Sustituir los valores NAN por 0 y guardar el cambio realizado.

In [7]:
liga21.fillna(0, inplace=True)

,Rk,Player,Nation,Pos,Squad,Age,Born,MP,Starts,Min,...,xG,npxG,xA,npxG+xA,xG.1,xA.1,xG+xA,npxG.1,npxG+xA.1,Matches
0,1,Sabit Abdulai\Sabit-Abdulai,gh GHA,MF,Getafe,21,1999,3,0,60,...,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00,Matches
1,2,Marcos Acuña\Marcos-Acuna,ar ARG,DF,Sevilla,28,1991,30,26,2330,...,1.1,1.1,2.8,4.0,0.04,0.11,0.15,0.04,0.15,Matches
2,3,Bobby Adekanye\Bobby-Adekanye,nl NED,FWMF,Cádiz,21,1999,3,0,36,...,0.2,0.2,0.0,0.2,0.43,0.00,0.43,0.43,0.43,Matches
3,4,Martin Agirregabiria\Martin-Agirregabiria,es ESP,DFMF,Alavés,24,1996,26,16,1558,...,0.2,0.2,0.9,1.1,0.01,0.05,0.06,0.01,0.06,Matches
4,5,Joseph Aidoo\Joseph-Aidoo,gh GHA,DF,Celta Vigo,24,1995,25,14,1289,...,0.8,0.8,0.6,1.4,0.06,0.04,0.10,0.06,0.10,Matches
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
577,578,Joseba Zaldúa\Joseba-Zaldua,es ESP,DF,Real Sociedad,28,1992,12,6,639,...,0.1,0.1,0.8,0.8,0.01,0.11,0.11,0.01,0.11,Matches
578,579,Oier Zarraga\Oier-Zarraga,es ESP,MF,Athletic Club,21,1999,5,1,100,...,0.1,0.1,0.0,0.1,0.08,0.04,0.13,0.08,0.13,Matches
579,580,Igor Zubeldia\Igor-Zubeldia,es ESP,DF,Real Sociedad,23,1997,24,21,1959,...,1.0,1.0,0.7,1.8,0.05,0.03,0.08,0.05,0.08,Matches
580,581,Martín Zubimendi\Martin-Zubimendi,es ESP,MF,Real Sociedad,21,1999,31,17,1882,...,0.6,0.6,0.6,1.1,0.03,0.03,0.05,0.03,0.05,Matches
581,582,Martin Ødegaard\Martin-Odegaard,no NOR,MFFW,Real Madrid,21,1998,7,3,234,...,0.1,0.1,0.4,0.5,0.04,0.15,0.19,0.04,0.19,Matches

Volver a comprobar la cantidad de valores NAN.

In [8]:
liga21.isna().sum()

Rk           0
Player       0
Nation       0
Pos          0
Squad        0
Age          0
Born         0
MP           0
Starts       0
Min          0
90s          0
Gls          0
Ast          0
G-PK         0
PK           0
PKatt        0
CrdY         0
CrdR         0
Gls.1        0
Ast.1        0
G+A          0
G-PK.1       0
G+A-PK       0
xG           0
npxG         0
xA           0
npxG+xA      0
xG.1         0
xA.1         0
xG+xA        0
npxG.1       0
npxG+xA.1    0
Matches      0
dtype: int64

1.7.  Eliminar la columna ``'Rk'`` y ``'matches'``. Recuerda guardar los cambios, después de eliminarlas realiza un .head() para ver el resultado.

In [9]:
liga21.drop(['Rk', 'Matches'], axis=1, inplace=True)
liga21.head(5)

,Player,Nation,Pos,Squad,Age,Born,MP,Starts,Min,90s,...,G+A-PK,xG,npxG,xA,npxG+xA,xG.1,xA.1,xG+xA,npxG.1,npxG+xA.1
0,Sabit Abdulai\Sabit-Abdulai,gh GHA,MF,Getafe,21,1999,3,0,60,0.7,...,0.00,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00
1,Marcos Acuña\Marcos-Acuna,ar ARG,DF,Sevilla,28,1991,30,26,2330,25.9,...,0.12,1.1,1.1,2.8,4.0,0.04,0.11,0.15,0.04,0.15
2,Bobby Adekanye\Bobby-Adekanye,nl NED,FWMF,Cádiz,21,1999,3,0,36,0.4,...,0.00,0.2,0.2,0.0,0.2,0.43,0.00,0.43,0.43,0.43
3,Martin Agirregabiria\Martin-Agirregabiria,es ESP,DFMF,Alavés,24,1996,26,16,1558,17.3,...,0.06,0.2,0.2,0.9,1.1,0.01,0.05,0.06,0.01,0.06
4,Joseph Aidoo\Joseph-Aidoo,gh GHA,DF,Celta Vigo,24,1995,25,14,1289,14.3,...,0.00,0.8,0.8,0.6,1.4,0.06,0.04,0.10,0.06,0.10

1.8. Solucionar el problema de  los nombres de los jugadores. Dejar el nombre en correcto estado.

In [10]:
liga21['Player'] = liga21.Player.apply(lambda name: name.split('\\')[0])
liga21.Player.head(5)

0           Sabit Abdulai
1            Marcos Acuña
2          Bobby Adekanye
3    Martin Agirregabiria
4            Joseph Aidoo
Name: Player, dtype: str

1.9. Solucionar el problema de la nacionalidad. Quedarnos con la nacionalidad que está en mayúsculas.

In [11]:
liga21['Nation']= liga21.Nation.apply(lambda nation : nation.split(' ')[1])
liga21.Nation.head(5)

0    GHA
1    ARG
2    NED
3    ESP
4    GHA
Name: Nation, dtype: str

1.10.  Solucionar el problema de las posiciones. Que cada jugador tenga unicamente una posicón.

Primero ver cuántas posiciones hay y cuanto se repite cada una.

In [12]:
liga21.Pos.value_counts()

Pos
DF      178
MF      130
FW       68
FWMF     64
MFFW     57
GK       40
MFDF     21
DFMF     17
DFFW      4
FWDF      2
GKMF      1
Name: count, dtype: int64

Utilizar ``.apply()`` y ``lambda`` para quedarnos con solo una posición.

In [13]:
liga21['Pos'] = liga21.Pos.apply(lambda pos : pos[:2] if len(pos) > 2 else pos)
liga21.Pos.value_counts()

Pos
MF    208
DF    199
FW    134
GK     41
Name: count, dtype: int64

1.11. Renombrar las columnas que contiene el valor .1, como por ejemplo ``'Ast.1'`` estas son columnas que pertenecen a las métricas por 90 min. Sustituir ``'Ast.1'`` por ``'Ast/90'``, hacer los mismo con las columnas que presentan este patrón

In [14]:
liga21.columns

Index(['Player', 'Nation', 'Pos', 'Squad', 'Age', 'Born', 'MP', 'Starts',
       'Min', '90s', 'Gls', 'Ast', 'G-PK', 'PK', 'PKatt', 'CrdY', 'CrdR',
       'Gls.1', 'Ast.1', 'G+A', 'G-PK.1', 'G+A-PK', 'xG', 'npxG', 'xA',
       'npxG+xA', 'xG.1', 'xA.1', 'xG+xA', 'npxG.1', 'npxG+xA.1'],
      dtype='str')

In [15]:
liga21 = liga21.rename(columns ={
    'Gls.1':'Gls/90',
    'Ast.1':'Ast/90',
    'G-PK.1':'G-PK/90',
    'xG.1':'xG/90',
    'xA.1':'xA/90',
    'npxG.1':'npxG/90',
    'npxG+xA.1':'npxG+xA/90'
})

Observar de nuevo el valor de las columnas para ver que se ha realizado el cambio correctamente.

In [16]:
liga21.columns

Index(['Player', 'Nation', 'Pos', 'Squad', 'Age', 'Born', 'MP', 'Starts',
       'Min', '90s', 'Gls', 'Ast', 'G-PK', 'PK', 'PKatt', 'CrdY', 'CrdR',
       'Gls/90', 'Ast/90', 'G+A', 'G-PK/90', 'G+A-PK', 'xG', 'npxG', 'xA',
       'npxG+xA', 'xG/90', 'xA/90', 'xG+xA', 'npxG/90', 'npxG+xA/90'],
      dtype='str')

1.12. Crear la función para automatizar todo el proceso, todos los procesos anteriores que hemos ido realizando los encapsularemos dentro de una función. La función se llamará ``transform_data()``, el único requisito es que tenga el parámetro de la ruta donde se encuentran los datos. Utilizar la # para nombrar lo que se hace en cada parte del código.

In [17]:
def transform_data(datapath):
    #leemos los datos desde el archivo
    liga21 = pd.read_csv(datapath)
    #Sustituimos los valores NAN por 0 y guardamos el cambio.
    liga21.fillna(0, inplace=True)
    #Eliminamos la columna 'Rk' y la columna 'Matches'
    liga21.drop(['Rk', 'Matches'], axis=1, inplace=True)
    #Solucionamos el problema de los nombres de los jugadores
    liga21['Player']= liga21.Player.apply(lambda name: name.split('\\')[0])
    #Solucionamos el problema de la nacionalidad
    liga21['Nation']= liga21.Nation.apply(lambda nation: nation.split(' ')[1])
    #Solucionamos el problema de las posiciones, quedandonos sólo con la primera
    liga21['Pos']= liga21.Pos.apply(lambda pos : pos[:2] if len (pos) > 2 else pos)
    #Cambiamos los nombres de las columnas
    liga21 = liga21.rename(columns ={
    'Gls.1':'Gls/90',
    'Ast.1':'Ast/90',
    'G-PK.1':'G-PK/90',
    'xG.1':'xG/90',
    'xA.1':'xA/90',
    'npxG.1':'npxG/90',
    'npxG+xA.1':'npxG+xA/90'
    })
    return liga21

Comprobar que nuestra función funciona correctamente, utilizando el path en donde se encuentran los datos. Guardar el resultado de salida en una variable y aplicarle ``.head()`` para comprobar que se han realizado todos las transformaciones.

In [18]:
test_function = transform_data('fbref_laliga21.csv')
test_function.head()

,Player,Nation,Pos,Squad,Age,Born,MP,Starts,Min,90s,...,G+A-PK,xG,npxG,xA,npxG+xA,xG/90,xA/90,xG+xA,npxG/90,npxG+xA/90
0,Sabit Abdulai,GHA,MF,Getafe,21,1999,3,0,60,0.7,...,0.00,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00
1,Marcos Acuña,ARG,DF,Sevilla,28,1991,30,26,2330,25.9,...,0.12,1.1,1.1,2.8,4.0,0.04,0.11,0.15,0.04,0.15
2,Bobby Adekanye,NED,FW,Cádiz,21,1999,3,0,36,0.4,...,0.00,0.2,0.2,0.0,0.2,0.43,0.00,0.43,0.43,0.43
3,Martin Agirregabiria,ESP,DF,Alavés,24,1996,26,16,1558,17.3,...,0.06,0.2,0.2,0.9,1.1,0.01,0.05,0.06,0.01,0.06
4,Joseph Aidoo,GHA,DF,Celta Vigo,24,1995,25,14,1289,14.3,...,0.00,0.8,0.8,0.6,1.4,0.06,0.04,0.10,0.06,0.10

# 2. Filtrado de los datos

2.1. Con la técnica ``.loc[]``, seleccinamene todas las filas de las siguientes columnas:

``'Player', 'Squad', 'Gls/90', 'Ast/90', 'xG/90', 'xA/90'``

In [19]:
liga21.loc[:,['Player', 'Squad', 'Gls/90', 'Ast/90', 'xG/90', 'xA/90']]

                   Player          Squad  Gls/90  Ast/90  xG/90  xA/90
0           Sabit Abdulai         Getafe    0.00    0.00   0.00   0.00
1            Marcos Acuña        Sevilla    0.04    0.08   0.04   0.11
2          Bobby Adekanye          Cádiz    0.00    0.00   0.43   0.00
3    Martin Agirregabiria         Alavés    0.00    0.06   0.01   0.05
4            Joseph Aidoo     Celta Vigo    0.00    0.00   0.06   0.04
..                    ...            ...     ...     ...    ...    ...
577         Joseba Zaldúa  Real Sociedad    0.00    0.00   0.01   0.11
578          Oier Zarraga  Athletic Club    0.00    0.00   0.08   0.04
579         Igor Zubeldia  Real Sociedad    0.05    0.05   0.05   0.03
580      Martín Zubimendi  Real Sociedad    0.00    0.00   0.03   0.03
581       Martin Ødegaard    Real Madrid    0.00    0.00   0.04   0.15

[582 rows x 6 columns]

2.2. Obtén únicamente el nombre de los equipos.

In [20]:
liga21.Squad.unique()

<StringArray>
[         'Getafe',         'Sevilla',           'Cádiz',          'Alavés',
      'Celta Vigo',           'Betis',           'Elche',       'Barcelona',
      'Villarreal',      'Valladolid',           'Eibar',   'Athletic Club',
         'Granada',   'Real Sociedad',     'Real Madrid',         'Osasuna',
         'Levante',        'Valencia',          'Huesca', 'Atlético Madrid']
Length: 20, dtype: str

2.3. Nuevamente con ``.loc[]`` selecciona los datos del Atlético de madrid de la siguiente columnas.

``'Player', 'Gls','xG','Gls/90','xG/90'``

In [21]:
liga21.loc[liga21.Squad == 'Atlético Madrid', ['Player', 'Gls', 'xG', 'Gls/90', 'xG/90']]

                 Player  Gls    xG  Gls/90  xG/90
92     Yannick Carrasco    6   6.0    0.25   0.25
112        Ángel Correa    9   7.6    0.34   0.29
115         Diego Costa    2   1.4    0.87   0.60
124      Moussa Dembélé    0   1.0    0.00   0.92
161              Felipe    0   0.9    0.00   0.04
162          João Félix    7   5.1    0.40   0.29
227       Mario Hermoso    1   1.2    0.03   0.04
229      Héctor Herrera    0   0.2    0.00   0.03
274                Koke    1   1.9    0.03   0.06
276  Geoffrey Kondogbia    0   0.2    0.00   0.02
291        Thomas Lemar    1   1.3    0.07   0.09
296     Marcos Llorente   12   4.3    0.37   0.13
297          Renan Lodi    1   0.7    0.08   0.06
323  José María Giménez    0   0.9    0.00   0.05
392         Saúl Ñíguez    2   2.7    0.09   0.12
399           Jan Oblak    0   0.0    0.00   0.00
417       Thomas Partey    0   0.1    0.00   0.05
464              Ricard    0   0.0    0.00   0.07
497      Manuel Sánchez    0   0.0    0.00   0.00
501        Stefan Savić    1   0.9    0.03   0.03
523         Luis Suárez   21  15.6    0.75   0.56
533      Lucas Torreira    1   0.2    0.17   0.04
540     Kieran Trippier    0   0.1    0.00   0.00
566              Vitolo    0   0.5    0.00   0.15
567       Šime Vrsaljko    0   0.0    0.00   0.00

2.4. Al filtrado anterior, añádele que me muestre también solo los delanteros del Atlético de Madrid con las columnas del ejercicio anterior.

In [22]:
liga21.loc[(liga21.Squad == 'Atlético Madrid') & (liga21.Pos == 'FW'), ['Player', 'Gls', 'xG', 'Gls/90', 'xG/90']]

             Player  Gls    xG  Gls/90  xG/90
112    Ángel Correa    9   7.6    0.34   0.29
115     Diego Costa    2   1.4    0.87   0.60
124  Moussa Dembélé    0   1.0    0.00   0.92
162      João Félix    7   5.1    0.40   0.29
523     Luis Suárez   21  15.6    0.75   0.56

2.5. Utilizando  también  las columnas del ejercicio anterior, quiero seleccionar los delanteros del Real Madrid y Atlético de Madrid. Ordenar los datos en función de la columna ``'Gls'`` y de manera descendiente.

In [23]:
liga21.loc[(liga21.Squad == 'Atlético Madrid') | (liga21.Squad == 'Real Madrid') & (liga21.Pos == 'FW'), ['Player', 'Gls', 'xG', 'Gls/90', 'xG/90']].sort_values('Gls', ascending=False)

                 Player  Gls    xG  Gls/90  xG/90
55        Karim Benzema   23  17.8    0.72   0.55
523         Luis Suárez   21  15.6    0.75   0.56
296     Marcos Llorente   12   4.3    0.37   0.13
112        Ángel Correa    9   7.6    0.34   0.29
162          João Félix    7   5.1    0.40   0.29
92     Yannick Carrasco    6   6.0    0.25   0.25
33        Marco Asensio    5   4.9    0.24   0.23
226         Eden Hazard    3   1.6    0.51   0.27
263     Vinicius Júnior    3   6.5    0.14   0.30
392         Saúl Ñíguez    2   2.7    0.09   0.12
115         Diego Costa    2   1.4    0.87   0.60
480             Rodrygo    1   2.5    0.09   0.23
227       Mario Hermoso    1   1.2    0.03   0.04
291        Thomas Lemar    1   1.3    0.07   0.09
533      Lucas Torreira    1   0.2    0.17   0.04
297          Renan Lodi    1   0.7    0.08   0.06
324             Mariano    1   1.5    0.18   0.26
501        Stefan Savić    1   0.9    0.03   0.03
274                Koke    1   1.9    0.03   0.06
31       Sergio Arribas    0   0.0    0.00   0.02
261          Luka Jović    0   1.1    0.00   0.67
276  Geoffrey Kondogbia    0   0.2    0.00   0.02
143           Hugo Duro    0   0.1    0.00   0.22
161              Felipe    0   0.9    0.00   0.04
124      Moussa Dembélé    0   1.0    0.00   0.92
229      Héctor Herrera    0   0.2    0.00   0.03
323  José María Giménez    0   0.9    0.00   0.05
464              Ricard    0   0.0    0.00   0.07
417       Thomas Partey    0   0.1    0.00   0.05
399           Jan Oblak    0   0.0    0.00   0.00
335       Borja Mayoral    0   0.0    0.00   0.00
497      Manuel Sánchez    0   0.0    0.00   0.00
540     Kieran Trippier    0   0.1    0.00   0.00
566              Vitolo    0   0.5    0.00   0.15
567       Šime Vrsaljko    0   0.0    0.00   0.00

2.6. Realizar una agrupación por los equipos, de las columnas ``'Gls', 'Ast', 'xG', 'xA'``
y calcula el promedio y el total para cada columna.

In [24]:
#Además, se ordenó según el equipo que marcó más goles.
liga21.groupby('Squad')[['Gls','Ast', 'xG', 'xA']].agg(['sum', 'mean']).sort_values(('Gls','sum'), ascending =False)

                Gls           Ast              xG              xA
                sum      mean sum      mean   sum      mean   sum      mean
Squad
Barcelona        80  3.200000  51  2.040000  80.2  3.208000  57.6  2.304000
Atlético Madrid  65  2.600000  54  2.160000  52.8  2.112000  37.9  1.516000
Real Madrid      64  2.133333  53  1.766667  62.7  2.090000  46.2  1.540000
Real Sociedad    58  1.933333  39  1.300000  61.5  2.050000  39.3  1.310000
Villarreal       57  1.965517  33  1.137931  58.5  2.017241  40.6  1.400000
Celta Vigo       55  1.833333  39  1.300000  48.3  1.610000  33.6  1.120000
Sevilla          52  2.000000  36  1.384615  51.5  1.980769  34.6  1.330769
Betis            50  2.000000  35  1.400000  47.4  1.896000  30.0  1.200000
Valencia         48  1.600000  35  1.166667  44.4  1.480000  27.1  0.903333
Granada          46  1.352941  30  0.882353  40.0  1.176471  23.8  0.700000
Levante          45  1.551724  35  1.206897  41.0  1.413793  27.7  0.955172
Athletic Club    43  1.592593  31  1.148148  44.8  1.659259  31.0  1.148148
Osasuna          36  1.285714  25  0.892857  38.3  1.367857  23.4  0.835714
Alavés           35  1.166667  21  0.700000  43.2  1.440000  25.8  0.860000
Valladolid       34  1.062500  21  0.656250  36.6  1.143750  22.2  0.693750
Cádiz            33  0.970588  16  0.470588  34.9  1.026471  19.2  0.564706
Elche            33  1.100000  25  0.833333  30.7  1.023333  21.9  0.730000
Huesca           32  1.185185  23  0.851852  35.7  1.322222  23.9  0.885185
Eibar            29  0.966667  20  0.666667  42.5  1.416667  26.4  0.880000
Getafe           27  0.870968  14  0.451613  32.8  1.058065  20.2  0.651613

# 3. Bucle for y condicionales

3.1. Vamos a realizar un bucle for donde iteraremos por los diferentes valores de la columna ``'Gls'`` para crear una nueva columna que se llamara ``'type_goal_player'``. Dejo a tu elección los valores en base dónde cortar para crear las diferentes categorías. Hay que crear tres valor Poco goleador, goleador, Muy goleador

In [25]:
liga21.Gls.unique()

array([ 0,  1,  3,  6,  2,  5, 14, 23,  8,  7,  4, 11,  9, 18, 13, 17, 12,
       30, 21])

In [26]:
len(liga21.Gls)

582

In [27]:
for i in range(len(liga21)):
  if liga21.Gls.values[i] <=15:
    liga21.loc[i, 'type_goal_player'] = 'Poco Goleador'

  elif (liga21.Gls.values[i] > 15) & (liga21.Gls.values[i] <=20):
    liga21.loc[i, 'type_goal_player'] = 'Goleador'

  else:
    liga21.loc[i, 'type_goal_player'] = 'Muy goleador'

3.2. Filtramos los datos para los jugadores que tienen el valor de ``'Muy goleador'`` en nuestra nueva columna.

In [28]:
liga21[liga21.type_goal_player == 'Muy goleador']

,Player,Nation,Pos,Squad,Age,Born,MP,Starts,Min,90s,...,xG,npxG,xA,npxG+xA,xG/90,xA/90,xG+xA,npxG/90,npxG+xA/90,type_goal_player
55,Karim Benzema,FRA,FW,Real Madrid,32,1987,34,33,2894,32.2,...,17.8,17.0,6.3,23.3,0.55,0.19,0.75,0.53,0.72,Muy goleador
344,Lionel Messi,ARG,FW,Barcelona,33,1987,35,33,3023,33.6,...,23.6,19.4,10.8,30.3,0.70,0.32,1.02,0.58,0.90,Muy goleador
369,Gerard Moreno,ESP,FW,Villarreal,28,1992,33,30,2673,29.7,...,19.1,11.6,7.6,19.2,0.64,0.26,0.90,0.39,0.65,Muy goleador
523,Luis Suárez,URU,FW,Atlético Madrid,33,1987,32,30,2508,27.9,...,15.6,13.3,3.3,16.6,0.56,0.12,0.68,0.48,0.59,Muy goleador

3.3. Quiero saber la cantidad de jugadores de cada tipo de goleador. Cuantas veces sale cada valor en la columna ``'type_goal_player'``.

In [29]:
liga21.type_goal_player.value_counts()

type_goal_player
Poco Goleador    576
Muy goleador       4
Goleador           2
Name: count, dtype: int64